BASE_URL = "https://api.0705.fun"
HOT_LIST_URL = BASE_URL + "/hotlist/index.php"
HOROSCOPE_URL = BASE_URL + "/horoscope/index.php"
ONE_WORD_URL = BASE_URL + "/one/index.php"
VIDEO_URL = BASE_URL + "/video/url.php"
HERO_POWER_URL = BASE_URL + "/hero/index.php"
FISH_URL = BASE_URL + "/moyu/index.php"
NEWS_URL = BASE_URL + "/news/index.php"
ZHU_GE_URL = BASE_URL + "/file/诸葛神签.txt"
IMAGE_URL = BASE_URL + "/file/image_qr_code.png"
IMAGE_TIPS_URL = BASE_URL + "/file/image_tips.png"
PETPET_URL = BASE_URL + "/petpet/index.php"
SETTING_URL = BASE_URL + "/setting.yml"
WEATHER_URL = BASE_URL + "/weather/index.php"
TAROT_URL = BASE_URL + "/tarot/index.php"
TAROT_IMG_URL = BASE_URL + "/tarot/img/"
WIFE_URL = BASE_URL + "/wife/index.php"
WIFE_IMG_URL = BASE_URL + "/wife/wives/"
MomoURL = "https://api.lolimi.cn/API/AI/mm.php?msg="
JingfengURL = "https://api.lolimi.cn/API/AI/jj.php?msg="
